<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'solid\\compatibleoptionscollectiontest' => '/CompatibleOptionsCollectionTest.php',
                'solid\\multipleoptionsproducttest' => '/MultipleOptionsProductTest.php',
                'solid\\nooptionproducttest' => '/NoOptionProductTest.php',
                'solid\\notsoswegoptiontest' => '/NotSoSwegOptionTest.php',
                'solid\\singleoptionproducttest' => '/SingleOptionProductTest.php',
                'solid\\swegoptiontest' => '/SwegOptionTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
