<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'solid\\baseoption' => '/Options/BaseOption.php',
                'solid\\compatibleoptionscollection' => '/CompatibleOptionsCollection.php',
                'solid\\multipleoptionsproduct' => '/Products/MultipleOptionsProduct.php',
                'solid\\nooptionproduct' => '/Products/NoOptionProduct.php',
                'solid\\notsoswegoption' => '/Options/NotSoSwegOption.php',
                'solid\\option' => '/Options/Option.php',
                'solid\\product' => '/Products/Product.php',
                'solid\\singleoptionproduct' => '/Products/SingleOptionProduct.php',
                'solid\\swegoption' => '/Options/SwegOption.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
